const Types = Object.freeze({
  TEST: 'TEST',
  Q2_SHOW_SELF_RESPONSE_BOX: 'Q2_SHOW_SELF_RESPONSE_BOX',
  Q2_HIDE_SELF_RESPONSE_BOX: 'Q2_HIDE_SELF_RESPONSE_BOX',
  Q3_SHOW_SELF_RESPONSE_BOX: 'Q3_SHOW_SELF_RESPONSE_BOX',
  Q3_HIDE_SELF_RESPONSE_BOX: 'Q3_HIDE_SELF_RESPONSE_BOX',
  Q12_SHOW_Q12A: 'Q12_SHOW_Q12A',
  Q12_HIDE_Q12A: 'Q12_HIDE_Q12A'
})

export default Types
