const Types = Object.freeze({
  TEST: 'TEST',
  SCAN: 'SCAN',
  USER_VALUES: 'USER_VALUES',
  SHOW_CAMERA: 'SHOW_CAMERA',
  HIDE_CAMERA: 'HIDE_CAMERA',
  SHOW_USER_REGISTERED_POP_UP: 'SHOW_USER_REGISTERED_POP_UP',
  HIDE_USER_REGISTERED_POP_UP: 'HIDE_USER_REGISTERED_POP_UP',
  SHOW_DEMO_SURVEY: 'SHOW_DEMO_SURVEY',
  HIDE_DEMO_SURVEY: 'HIDE_DEMO_SURVEY'
})

export default Types
